name: paddle_jakarta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dartz:
  hive:
  hive_flutter:
  cloud_firestore:
  google_sign_in:
  firebase_auth:
  firebase_core:
  firebase_storage:
  google_fonts: ^6.2.1
  lucide_icons:
  flutter_any_logo: 
  flutter_svg:

dependency_overrides:
  flutter_any_logo:
    git:
      url: https://github.com/elmermj/flutter_any_logo.git
      ref: main

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/firebase_options.json
