import 'package:hive_flutter/hive_flutter.dart';

// part 'app_settings.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 1)
class AppSettings extends HiveObject {
  @HiveField(0)
  bool? themeDarkMode;

  @HiveField(1)
  bool isNewApplication = true;

  // Getter for theme mode
  bool get isDarkMode => themeDarkMode ?? false; // Default to false if null
  
  // Setter for theme mode
  set isDarkMode(bool value) => themeDarkMode = value;

  // Method to initialize with default values
  static Future<AppSettings> initialize() async {
    final box = await Hive.openBox<AppSettings>('app_settings');
    final settings = box.get('settings', defaultValue: AppSettings())!;
    return settings;
  }
}
