name: Dart

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.24.1

    - run: flutter --version

    - name: Set up Firebase Options
      run: |
        mkdir -p assets
        echo "${{ secrets.DEV_FIREBASE_CONFIG }}" | base64 --decode > assets/firebase_options.json

    - name: Set up Google Services
      run: |
        mkdir -p android/app
        echo "${{ secrets.DEV_GOOGLE_SERVICES }}" | base64 --decode > android/app/google-services.json

    - name: Install dependencies
      run: dart pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload development APK to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_BASE64 }}
        filename: "build/app/outputs/flutter-apk/app-release.apk"
        folderId: ${{ secrets.FOLDER_ID }}
        name: "app-release.apk"
        overwrite: "true"

